<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMenuItemSegmentation extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('menu_items', function (Blueprint $table) {
            $table->string('segmentation_any',30)->nullable()->after('segmentation');
            $table->string('segmentation_bbd',30)->nullable()->after('segmentation_any');
            $table->string('segmentation_eyb',30)->nullable()->after('segmentation_bbd');
            $table->string('segmentation_cbl',30)->nullable()->after('segmentation_eyb');
            $table->string('segmentation_com',30)->nullable()->after('segmentation_cbl');
            $table->string('segmentation_fmr',30)->nullable()->after('segmentation_com');
            $table->string('segmentation_fwb',30)->nullable()->after('segmentation_fmr');
            $table->string('segmentation_fzb',30)->nullable()->after('segmentation_fwb');
            $table->string('segmentation_hmk',30)->nullable()->after('segmentation_fzb');
            $table->string('segmentation_htw',30)->nullable()->after('segmentation_hmk');
            $table->string('segmentation_kkd',30)->nullable()->after('segmentation_htw');
            $table->string('segmentation_lps',30)->nullable()->after('segmentation_kkd');
            $table->string('segmentation_lbs',30)->nullable()->after('segmentation_lps');
            $table->string('segmentation_mtd',30)->nullable()->after('segmentation_lbs');
            $table->string('segmentation_ppd',30)->nullable()->after('segmentation_mtd');
            $table->string('segmentation_pze',30)->nullable()->after('segmentation_ppd');
            $table->string('segmentation_psn',30)->nullable()->after('segmentation_pze');
            $table->string('segmentation_ppr',30)->nullable()->after('segmentation_psn');
            $table->string('segmentation_rcf',30)->nullable()->after('segmentation_ppr');
            $table->string('segmentation_scb',30)->nullable()->after('segmentation_rcf');
            $table->string('segmentation_sch',30)->nullable()->after('segmentation_scb');
            $table->string('segmentation_sdh',30)->nullable()->after('segmentation_sch');
            $table->string('segmentation_smk',30)->nullable()->after('segmentation_sdh');
            $table->string('segmentation_twu',30)->nullable()->after('segmentation_smk');
            $table->string('segmentation_tbf',30)->nullable()->after('segmentation_twu');
            $table->string('segmentation_tgd',30)->nullable()->after('segmentation_tbf');
            $table->string('segmentation_wkd',30)->nullable()->after('segmentation_tgd');
            $table->string('segmentation_wks',30)->nullable()->after('segmentation_wkd');
            $table->string('segmentation_wmn',30)->nullable()->after('segmentation_wks');
            $table->string('segmentation_1',30)->nullable()->after('segmentation_wmn');
            $table->string('segmentation_2',30)->nullable()->after('segmentation_1');
            $table->string('segmentation_3',30)->nullable()->after('segmentation_2');
            $table->string('segmentation_4',30)->nullable()->after('segmentation_3');
            $table->string('segmentation_5',30)->nullable()->after('segmentation_4');
            $table->string('segmentation_6',30)->nullable()->after('segmentation_5');
            $table->string('segmentation_7',30)->nullable()->after('segmentation_6');
            $table->string('segmentation_8',30)->nullable()->after('segmentation_7');
            $table->string('segmentation_9',30)->nullable()->after('segmentation_8');
            $table->string('segmentation_10',30)->nullable()->after('segmentation_9');
            $table->string('segmentation_11',30)->nullable()->after('segmentation_10');
            $table->string('segmentation_12',30)->nullable()->after('segmentation_11');
            $table->string('segmentation_13',30)->nullable()->after('segmentation_12');
            $table->string('segmentation_14',30)->nullable()->after('segmentation_13');
            $table->string('segmentation_30',30)->nullable()->after('segmentation_14');
            $table->string('segmentation_16',30)->nullable()->after('segmentation_30');
            $table->string('segmentation_17',30)->nullable()->after('segmentation_16');
            $table->string('segmentation_18',30)->nullable()->after('segmentation_17');
            $table->string('segmentation_19',30)->nullable()->after('segmentation_18');
            $table->string('segmentation_20',30)->nullable()->after('segmentation_19');
            $table->string('segmentation_21',30)->nullable()->after('segmentation_20');
            $table->string('segmentation_22',30)->nullable()->after('segmentation_21');
            $table->string('segmentation_slb',30)->nullable()->after('segmentation_22');
            $table->string('segmentation_dgb',30)->nullable()->after('segmentation_slb');
            $table->string('segmentation_scp',30)->nullable()->after('segmentation_dgb');
            $table->string('segmentation_sck',30)->nullable()->after('segmentation_scp');
            $table->string('segmentation_tdc',30)->nullable()->after('segmentation_sck');
            $table->string('segmentation_twn',30)->nullable()->after('segmentation_tdc');
            $table->string('segmentation_rcs',30)->nullable()->after('segmentation_twn');
            $table->string('segmentation_bob',30)->nullable()->after('segmentation_rcs');
            $table->string('segmentation_drp',30)->nullable()->after('segmentation_bob');
            $table->string('segmentation_bev',30)->nullable()->after('segmentation_drp');
            $table->string('segmentation_ten',30)->nullable()->after('segmentation_bev');
            $table->string('segmentation_ahw',30)->nullable()->after('segmentation_ten');
            $table->string('segmentation_tmt',30)->nullable()->after('segmentation_ahw');
            $table->string('segmentation_mks',30)->nullable()->after('segmentation_tmt');
            $table->string('segmentation_bkh',30)->nullable()->after('segmentation_mks');
            $table->string('segmentation_mni',30)->nullable()->after('segmentation_bkh');
            $table->string('segmentation_mor',30)->nullable()->after('segmentation_mni');
            $table->string('segmentation_kkg',30)->nullable()->after('segmentation_mor');
            $table->string('segmentation_fab',30)->nullable()->after('segmentation_kkg');
            $table->string('segmentation_tai',30)->nullable()->after('segmentation_fab');
            $table->string('segmentation_sea',30)->nullable()->after('segmentation_tai');
            $table->string('segmentation_tbb',30)->nullable()->after('segmentation_sea');
            $table->string('segmentation_wft',30)->nullable()->after('segmentation_tbb');
            $table->string('segmentation_spc',30)->nullable()->after('segmentation_wft');
            $table->string('segmentation_spb',30)->nullable()->after('segmentation_spc');
            $table->string('segmentation_crp',30)->nullable()->after('segmentation_spb');
            $table->string('segmentation_cor',30)->nullable()->after('segmentation_crp');
            $table->string('segmentation_cpl',30)->nullable()->after('segmentation_cor');
            $table->string('segmentation_cmp',30)->nullable()->after('segmentation_cpl');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('menu_items', function (Blueprint $table) {
            $table->dropColumn('segmentation_any');
            $table->dropColumn('segmentation_bbd');
            $table->dropColumn('segmentation_eyb');
            $table->dropColumn('segmentation_cbl');
            $table->dropColumn('segmentation_com');
            $table->dropColumn('segmentation_fmr');
            $table->dropColumn('segmentation_fwb');
            $table->dropColumn('segmentation_fzb');
            $table->dropColumn('segmentation_hmk');
            $table->dropColumn('segmentation_htw');
            $table->dropColumn('segmentation_kkd');
            $table->dropColumn('segmentation_lps');
            $table->dropColumn('segmentation_lbs');
            $table->dropColumn('segmentation_mtd');
            $table->dropColumn('segmentation_ppd');
            $table->dropColumn('segmentation_pze');
            $table->dropColumn('segmentation_psn');
            $table->dropColumn('segmentation_ppr');
            $table->dropColumn('segmentation_rcf');
            $table->dropColumn('segmentation_scb');
            $table->dropColumn('segmentation_sch');
            $table->dropColumn('segmentation_sdh');
            $table->dropColumn('segmentation_smk');
            $table->dropColumn('segmentation_twu');
            $table->dropColumn('segmentation_tbf');
            $table->dropColumn('segmentation_tgd');
            $table->dropColumn('segmentation_wkd');
            $table->dropColumn('segmentation_wks');
            $table->dropColumn('segmentation_wmn');
            $table->dropColumn('segmentation_1');
            $table->dropColumn('segmentation_2');
            $table->dropColumn('segmentation_3');
            $table->dropColumn('segmentation_4');
            $table->dropColumn('segmentation_5');
            $table->dropColumn('segmentation_6');
            $table->dropColumn('segmentation_7');
            $table->dropColumn('segmentation_8');
            $table->dropColumn('segmentation_9');
            $table->dropColumn('segmentation_10');
            $table->dropColumn('segmentation_11');
            $table->dropColumn('segmentation_12');
            $table->dropColumn('segmentation_13');
            $table->dropColumn('segmentation_14');
            $table->dropColumn('segmentation_15');
            $table->dropColumn('segmentation_16');
            $table->dropColumn('segmentation_17');
            $table->dropColumn('segmentation_18');
            $table->dropColumn('segmentation_19');
            $table->dropColumn('segmentation_20');
            $table->dropColumn('segmentation_21');
            $table->dropColumn('segmentation_22');
            $table->dropColumn('segmentation_slb');
            $table->dropColumn('segmentation_dgb');
            $table->dropColumn('segmentation_scp');
            $table->dropColumn('segmentation_sck');
            $table->dropColumn('segmentation_tdc');
            $table->dropColumn('segmentation_twn');
            $table->dropColumn('segmentation_rcs');
            $table->dropColumn('segmentation_bob');
            $table->dropColumn('segmentation_drp');
            $table->dropColumn('segmentation_bev');
            $table->dropColumn('segmentation_ten');
            $table->dropColumn('segmentation_ahw');
            $table->dropColumn('segmentation_tmt');
            $table->dropColumn('segmentation_mks');
            $table->dropColumn('segmentation_bkh');
            $table->dropColumn('segmentation_mni');
            $table->dropColumn('segmentation_mor');
            $table->dropColumn('segmentation_kkg');
            $table->dropColumn('segmentation_fab');
            $table->dropColumn('segmentation_tai');
            $table->dropColumn('segmentation_sea');
            $table->dropColumn('segmentation_tbb');
            $table->dropColumn('segmentation_wft');
            $table->dropColumn('segmentation_spc');
            $table->dropColumn('segmentation_spb');
            $table->dropColumn('segmentation_crp');
            $table->dropColumn('segmentation_cor');
            $table->dropColumn('segmentation_cpl');
            $table->dropColumn('segmentation_cmp');

        });
    }
}
